-- AlterTable
ALTER TABLE `auditoria_admin` MODIFY `acao` ENUM('MORADOR_APROVADO', 'MORADOR_RECUSADO', 'USUARIO_INATIVADO', 'USUARIO_REATIVADO', 'SENHA_REDEFINIDA', 'SUBSINDICO_DEFINIDO', 'SUBSINDICO_REMOVIDO', 'CONDOMINIO_ATUALIZADO') NOT NULL;

-- AlterTable
ALTER TABLE `condominio` ADD COLUMN `cidade` VARCHAR(80) NULL,
    ADD COLUMN `uf` ENUM('AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO') NULL;
